version: "3"
services:
  client:
    container_name: client
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./api:/app
